### ISSUE TITLE
graceful stop

### ISSUE THREAD

**Issue by thesues** [bd-iaas-us/infiniStore#37]
each ctrl-c will crash, do not know why
```
Server config: ServerConfig(service_port=22345, manage_port=18080, log_level='warning')
[2024-10-17 01:37:55.847] [infini] [info] Can't find or failed to open the specified device, try to open the default device
[2024-10-17 01:37:55.851] [infini] [info] Memory pool size: 17179869184 bytes, block size: 32768 bytes, total blocks: 524288, it may take a while
[2024-10-17 01:38:02.469] [infini] [info] Memory pool allocated at 0x7f5354000000
[2024-10-17 01:38:03.235] [infini] [info] register server done
[2024-10-17 01:38:32.952] [infini] [info] new connection...
[2024-10-17 01:38:32.968] [infini] [info] HEADER: op: E, body_size :24
[2024-10-17 01:38:32.968] [infini] [info] do rdma exchange...
[2024-10-17 01:38:32.973] [infini] [info] gid index: 3
[2024-10-17 01:38:32.974] [infini] [info] RDMA exchange done
[2024-10-17 01:38:33.240] [infini] [info] HEADER: op: D, body_size :20
[2024-10-17 01:38:33.240] [infini] [info] do rdma write keys: 3, remote_block_size: 4096
[2024-10-17 01:38:33.240] [infini] [info] response error code 202
[2024-10-17 01:38:50.407] [infini] [info] destroy cuda stream
[2024-10-17 01:38:50.409] [infini] [info] QP destroyed
^CTraceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/infinity/infinistore/server.py", line 112, in <module>
    main()
  File "/root/infinity/infinistore/server.py", line 108, in main
    loop.run_until_complete(server.serve())
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/data00/anaconda3/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    with self.capture_signals():
  File "/data00/anaconda3/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/data00/anaconda3/lib/python3.11/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
Segmentation fault (core dumped)
```

**Comment by thesues** [comment]
```
	rm -rf ../infinistore/$(PYBIND_TARGET)
	cp $(PYBIND_TARGET) ../infinistore/
```

use this to fix this.
