### ISSUE TITLE
unable to register multiple MR in the same location in rdma connection

### ISSUE THREAD

**Issue by chenqianfzh** [bd-iaas-us/infiniStore#85]
Repro step:

1. start infinistore with command from branch sync_cuda
```
infinistore --dev-name mlx5_0 --link-type Ethernet --prealloc-size 50  
```
2. start prefill & decode instance as well as kv transfer proxy from branch https://github.com/bd-iaas-us/vllm/tree/qian/fix-hidden-states-save

3. send out a request to the proxy like:

```
curl http://10.192.18.145:8080/v1/completions    -H "Content-Type: application/json"   -d '{"model": "mistralai/Mistral-7B-Instruct-v0.3", "prompt": "San Francisco is a", "max_tokens": 100}'
```
this command will return correct result.

4. However, if run the benchmark tool to send out multiple requests, 

will hit the following error in the prefill side:
```
ERROR 12-18 21:16:48 engine.py:135] Exception('Error in model execution (input dumped to /tmp/err_execute_model_input_20241218-211648.pkl): register memory region failed')
ERROR 12-18 21:16:48 engine.py:135] Traceback (most recent call last):
ERROR 12-18 21:16:48 engine.py:135]   File "/data00/qian/git/vllm/vllm/worker/model_runner_base.py", line 116, in _wrapper
ERROR 12-18 21:16:48 engine.py:135]     return func(*args, **kwargs)
ERROR 12-18 21:16:48 engine.py:135]   File "/data00/qian/git/vllm/vllm/worker/model_runner.py", line 1683, in execute_model
ERROR 12-18 21:16:48 engine.py:135]     hidden_or_intermediate_states = model_executable(
ERROR 12-18 21:16:48 engine.py:135]   File "/data00/miniconda3/envs/qian-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 12-18 21:16:48 engine.py:135]     return self._call_impl(*args, **kwargs)
ERROR 12-18 21:16:48 engine.py:135]   File "/data00/miniconda3/envs/qian-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 12-18 21:16:48 engine.py:135]     return forward_call(*args, **kwargs)
ERROR 12-18 21:16:48 engine.py:135]   File "/data00/qian/git/vllm/vllm/model_executor/models/llama.py", line 610, in forward
ERROR 12-18 21:16:48 engine.py:135]     model_output = self.model(input_ids, positions, kv_caches,
ERROR 12-18 21:16:48 engine.py:135]   File "/data00/qian/git/vllm/vllm/compilation/decorators.py", line 168, in __call__
ERROR 12-18 21:16:48 engine.py:135]     return self.forward(*args, **kwargs)
ERROR 12-18 21:16:48 engine.py:135]   File "/data00/qian/git/vllm/vllm/model_executor/models/llama.py", line 374, in forward
ERROR 12-18 21:16:48 engine.py:135]     kv_cache_transporter.read_hidden_states(input_token_hashes,
ERROR 12-18 21:16:48 engine.py:135]   File "/data00/qian/git/vllm/vllm/distributed/kv_transfer/infinite.py", line 247, in read_hidden_states
ERROR 12-18 21:16:48 engine.py:135]     self.rdma_conn.register_mr(hidden_states)
ERROR 12-18 21:16:48 engine.py:135]   File "/root/infinity/infinistore/lib.py", line 368, in register_mr
ERROR 12-18 21:16:48 engine.py:135]     raise Exception("register memory region failed")
ERROR 12-18 21:16:48 engine.py:135] Exception: register memory region failed
ERROR 12-18 21:16:48 engine.py:135] 
```

No error log in infinistore. 

The benchmark tool command I used:
```
rm -rf /tmp/infinistore/* > /dev/null 2>&1 & python3 benchmarks/benchmark_serving.py     --port 8080     --backend vllm     --dataset-name booksum    --dataset-path /data00/qian/git/vllm/booksum_data.csv    --model mistralai/Mistral-7B-Instruct-v0.3   --num-prompts  10 --endpoint /v1/completions  --request-rate 2 --gpu-metric-interval  0.5 --booksum-output-len 100 --booksum-fix-prompt-len 5000
```

**Comment by thesues** [comment]
I have 2 proposals

1. upper layer makes sure if it is the same region, do no call register Mr
2. register mr will have more detections. If the same range, skip.  if any overlap happens, log warning and merge. if no overlap, register it. 

I personally like option 2 @lyppg

**Comment by chenqianfzh** [comment]
ran into some other issues. Keep the issue open for now.
